FROM debian:stable-slim

RUN apt-get update \
    && apt-get install -y gnucobol \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY presentation.cob .

RUN cobc -x -free -o presentation presentation.cob

CMD ["./presentation"]
