FROM debian:stable-slim

RUN apt-get update \
    && apt-get install -y gnucobol \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY hello_world.cob .

RUN cobc -x -free -o hello_world hello_world.cob

CMD ["./hello_world"]
